/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.br.udesc.livroia.recommender;

import com.br.udesc.livroia.misc.FilesOperation;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author jordan
 */
public class PanelRecommender extends javax.swing.JPanel {

    /**
     * Creates new form PanelRecommender
     */
    public PanelRecommender() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LabFileCrowdRankingSelect = new javax.swing.JLabel();
        ButFileCrowdRankingSelect = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TexFileUserRankingSelect = new javax.swing.JTextArea();
        LabFileUserRankingSelect = new javax.swing.JLabel();
        ButFileUserRankingSelect = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TexFileCrowdRankingSelect = new javax.swing.JTextArea();
        PanResults = new javax.swing.JPanel();
        LabResults = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TexResults = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        ButExecute = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        setLayout(new java.awt.BorderLayout());

        LabFileCrowdRankingSelect.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabFileCrowdRankingSelect.setText("Selecione o arquivo de ranking DOS USUÁRIOS: ");

        ButFileCrowdRankingSelect.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        ButFileCrowdRankingSelect.setText("selecione");
        ButFileCrowdRankingSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButFileCrowdRankingSelectActionPerformed(evt);
            }
        });

        TexFileUserRankingSelect.setColumns(20);
        TexFileUserRankingSelect.setRows(5);
        jScrollPane1.setViewportView(TexFileUserRankingSelect);

        LabFileUserRankingSelect.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabFileUserRankingSelect.setText("Selecione o arquivo de preferências DO USUÁRIO: ");

        ButFileUserRankingSelect.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        ButFileUserRankingSelect.setText("selecione");
        ButFileUserRankingSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButFileUserRankingSelectActionPerformed(evt);
            }
        });

        TexFileCrowdRankingSelect.setColumns(20);
        TexFileCrowdRankingSelect.setRows(5);
        jScrollPane2.setViewportView(TexFileCrowdRankingSelect);

        PanResults.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        LabResults.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LabResults.setText("Recomendações para o usuário:");

        TexResults.setColumns(20);
        TexResults.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        TexResults.setRows(5);
        jScrollPane3.setViewportView(TexResults);

        javax.swing.GroupLayout PanResultsLayout = new javax.swing.GroupLayout(PanResults);
        PanResults.setLayout(PanResultsLayout);
        PanResultsLayout.setHorizontalGroup(
            PanResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanResultsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(PanResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabResults)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanResultsLayout.setVerticalGroup(
            PanResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanResultsLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(LabResults)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LabFileCrowdRankingSelect, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                        .addGap(44, 44, 44)
                        .addComponent(ButFileCrowdRankingSelect))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(LabFileUserRankingSelect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButFileUserRankingSelect)))
                .addGap(102, 102, 102)
                .addComponent(PanResults, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(PanResults, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabFileCrowdRankingSelect)
                            .addComponent(ButFileCrowdRankingSelect))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabFileUserRankingSelect)
                            .addComponent(ButFileUserRankingSelect))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)))
                .addGap(16, 16, 16))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(0, 51, 153));
        jPanel2.setAlignmentX(0.0F);
        jPanel2.setAlignmentY(0.0F);
        jPanel2.setFocusable(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(1398, 70));

        ButExecute.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ButExecute.setText("Executar");
        ButExecute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButExecuteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(1258, Short.MAX_VALUE)
                .addComponent(ButExecute)
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(ButExecute)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setBackground(new java.awt.Color(0, 51, 153));
        jPanel3.setAlignmentX(0.0F);
        jPanel3.setAlignmentY(0.0F);
        jPanel3.setEnabled(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(1398, 70));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Problemas de Recomendação");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addContainerGap(841, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        add(jPanel3, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void ButFileUserRankingSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButFileUserRankingSelectActionPerformed
        try {
            // TODO add your handling code here:
            TexFileUserRankingSelect.setText(FilesOperation.getDataFromFileSelected());
            TexFileUserRankingSelect.setCaretPosition(0);
        } catch (IOException ex) {
            Logger.getLogger(PanelRecommender.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ButFileUserRankingSelectActionPerformed

    private void ButFileCrowdRankingSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButFileCrowdRankingSelectActionPerformed
        try {
            //System.out.println(FilesOperation.getFileNameSelectOnDisk());
            TexFileCrowdRankingSelect.setText(FilesOperation.getDataFromFileSelected());
            TexFileCrowdRankingSelect.setCaretPosition(0);
            
        } catch (IOException ex) {
            Logger.getLogger(PanelRecommender.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ButFileCrowdRankingSelectActionPerformed

    private void ButExecuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButExecuteActionPerformed
        try {
            // TODO add your handling code here:
            // both data files must be selected
            if ((TexFileCrowdRankingSelect.getText().length()==0) || (TexFileUserRankingSelect.getText().length()==0)){
                JOptionPane.showMessageDialog(this, "Você precisa selecionar o arquivo de dados de ranking dos usuários e do usuário para receber a recomendação");
            }else{
                TexResults.setText(RecommenderService.run(new ByteArrayInputStream(TexFileCrowdRankingSelect.getText().getBytes()), new ByteArrayInputStream(TexFileUserRankingSelect.getText().getBytes())));
            }
        } catch (Exception ex) {
            Logger.getLogger(PanelRecommender.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ButExecuteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButExecute;
    private javax.swing.JButton ButFileCrowdRankingSelect;
    private javax.swing.JButton ButFileUserRankingSelect;
    private javax.swing.JLabel LabFileCrowdRankingSelect;
    private javax.swing.JLabel LabFileUserRankingSelect;
    private javax.swing.JLabel LabResults;
    private javax.swing.JPanel PanResults;
    private javax.swing.JTextArea TexFileCrowdRankingSelect;
    private javax.swing.JTextArea TexFileUserRankingSelect;
    private javax.swing.JTextArea TexResults;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
